-- FS1/FS2 are expected to fail on base code: the route snapshot and replay tools do not exist there.
local H = require "tests.harness"
local function run(command)
    local p = assert(io.popen(command .. " 2>&1", "r"))
    local out = p:read("*a")
    p:close()
    return out
end
H.test("FS1 failed route demand snapshots and replays alone", function()
    local snap = os.tmpname()
    local out = run("lua5.2 tools/route_fail_snapshot.lua tests/fixtures/route_gray_magenta_154.json 1 " .. snap)
    H.equal(out:match("SNAPSHOT"), "SNAPSHOT", "snapshot was written")
    H.equal(out:match("item/coal"), "item/coal", "first failure is coal")
    H.equal(out:match("in:item/coal:inserter:plastic%-bar:2:input:1") ~= nil, true, "expected sink")
    H.equal(out:match("BP_R_NO_PATH") ~= nil, true, "expected no path failure")
    local replay = run("lua5.2 tools/route_replay_one.lua " .. snap)
    H.equal(replay:match("REPLAY failed") ~= nil, true, "replay fails same demand")
    H.equal(replay:match("route%-discontinuous") ~= nil, true, "same route rejection")
    local seconds = tonumber(replay:match(" t=([%d%.]+)s"))
    H.equal(seconds ~= nil and seconds < 10, true, "replay under ten CPU seconds")
    H.test("FS2 in-memory patch can place replayed demand", function()
        local patch = os.tmpname()
        local f = assert(io.open(patch, "w"))
        f:write([[return function(src) return (src:gsub('and not %(current.mode == 1 and search.demand.kind == "pipe"%)', 'and not (current.mode == 1)', 1)) end]])
        f:close()
        local patched = run("PATCH=" .. patch .. " lua5.2 tools/route_replay_one.lua " .. snap)
        H.equal(patched:match("REPLAY placed") ~= nil, true, "patched route places demand")
        os.remove(patch)
    end)
    os.remove(snap)
end)
H.done("test_route_fail_snapshot")
