return {
 id = "lane_mix_bad", rule = "BP_V_LANE_MIX", class = "engine", from = "tests/test_validate_rows.lua VL2 paired flows entering from one side",
 grid = {w = 20, h = 20},
 entities = {
  {id = "feed-a", kind = "belt", name = "transport-belt", x = 0, y = 10, dir = "east", flow_id = "item/copper-plate"},
  {id = "feed-b0", kind = "belt", name = "transport-belt", x = 1, y = 0, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b1", kind = "belt", name = "transport-belt", x = 1, y = 1, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b2", kind = "belt", name = "transport-belt", x = 1, y = 2, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b3", kind = "belt", name = "transport-belt", x = 1, y = 3, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b4", kind = "belt", name = "transport-belt", x = 1, y = 4, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b5", kind = "belt", name = "transport-belt", x = 1, y = 5, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b6", kind = "belt", name = "transport-belt", x = 1, y = 6, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b7", kind = "belt", name = "transport-belt", x = 1, y = 7, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b8", kind = "belt", name = "transport-belt", x = 1, y = 8, dir = "south", flow_id = "item/iron-plate"},
  {id = "feed-b9", kind = "belt", name = "transport-belt", x = 1, y = 9, dir = "south", flow_id = "item/iron-plate"},
  {id = "merge", kind = "belt", name = "transport-belt", x = 1, y = 10, dir = "east"},
  {id = "run", kind = "belt", name = "transport-belt", x = 2, y = 10, dir = "east"},
  {id = "row-input", kind = "inserter", name = "inserter", x = 1, y = 11, dir = "south", role = "input", flow_ids = {"item/copper-plate", "item/iron-plate"}, pickup_position = {x = 1.5, y = 10.5}, drop_position = {x = 1.5, y = 12.5}},
  {id = "machine", kind = "machine", name = "assembling-machine-1", x = 1, y = 12, w = 3, h = 3, recipe = "iron-gear-wheel"},
  {id = "power", kind = "pole", name = "substation", x = 4, y = 11, w = 2, h = 2},
 },
 feeds = {{tile = {0, 10}, item = "copper-plate"}, {tile = {1, 0}, item = "iron-plate"}},
 --the run end drains into a sink that wants only the machine's iron: copper riding the same lanes reaches it.
 sinks = {{tile = {2, 10}, items = {"iron-plate"}}},
 validator = {catalog = {entity = {
  inserter = {name = "inserter", etype = "inserter", tile_w = 1, tile_h = 1, needs_power = false, items_per_second = 10},
  ["assembling-machine-1"] = {name = "assembling-machine-1", etype = "assembling-machine", tile_w = 3, tile_h = 3, needs_power = false},
  substation = {name = "substation", etype = "electric-pole", tile_w = 2, tile_h = 2, supply_w = 9, supply_h = 9, wire_reach = 18, needs_power = false},
 }, inserter = {items_per_second = 10, pickup_offset = {x = 0, y = 1}, drop_offset = {x = 0, y = -1}}, belt = {items_per_second = 10}, recipe = { ["iron-gear-wheel"] = {ingredients = {{name = "iron-plate"}}, products = {{name = "iron-gear-wheel"}}}}}},
 check = "flow_purity", truth = "defect", codes = {"BP_V_LANE_MIX"}, audit = {lane_sim = {mixed = 1, starved = 0, bleed = 0}},
}
