return {
 id = "ug_sideload_bad", rule = "BP_V_UNDERGROUND_SIDELOAD_BLOCKED", class = "engine", from = "tests/test_validate_transport_shapes.lua TS2b blocked lane",
 grid = {w = 20, h = 20},
 entities = {
  {id = "cross0", kind = "belt", name = "transport-belt", x = 0, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross1", kind = "belt", name = "transport-belt", x = 1, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross2", kind = "belt", name = "transport-belt", x = 2, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross3", kind = "belt", name = "transport-belt", x = 3, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross4", kind = "belt", name = "transport-belt", x = 4, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross5", kind = "belt", name = "transport-belt", x = 5, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross6", kind = "belt", name = "transport-belt", x = 6, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross7", kind = "belt", name = "transport-belt", x = 7, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross8", kind = "belt", name = "transport-belt", x = 8, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross9", kind = "belt", name = "transport-belt", x = 9, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross10", kind = "belt", name = "transport-belt", x = 10, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross11", kind = "belt", name = "transport-belt", x = 11, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross12", kind = "belt", name = "transport-belt", x = 12, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross13", kind = "belt", name = "transport-belt", x = 13, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "cross14", kind = "belt", name = "transport-belt", x = 14, y = 10, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge0", kind = "belt", name = "transport-belt", x = 0, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge1", kind = "belt", name = "transport-belt", x = 1, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge2", kind = "belt", name = "transport-belt", x = 2, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge3", kind = "belt", name = "transport-belt", x = 3, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge4", kind = "belt", name = "transport-belt", x = 4, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge5", kind = "belt", name = "transport-belt", x = 5, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge6", kind = "belt", name = "transport-belt", x = 6, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge7", kind = "belt", name = "transport-belt", x = 7, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge8", kind = "belt", name = "transport-belt", x = 8, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge9", kind = "belt", name = "transport-belt", x = 9, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge10", kind = "belt", name = "transport-belt", x = 10, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge11", kind = "belt", name = "transport-belt", x = 11, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge12", kind = "belt", name = "transport-belt", x = 12, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge13", kind = "belt", name = "transport-belt", x = 13, y = 8, dir = "east", flow_id = "item/iron-plate"},
  {id = "edge14", kind = "belt", name = "transport-belt", x = 14, y = 8, dir = "north", flow_id = "item/iron-plate"},
  {id = "hand", kind = "inserter", name = "inserter", x = 14, y = 9, dir = "north", flow_id = "item/iron-plate", needs_power = false, pickup_position = {x = 14.5, y = 10.5}, drop_position = {x = 14.5, y = 8.5}},
  {id = "north7", kind = "belt", name = "transport-belt", x = 14, y = 7, dir = "north", flow_id = "item/iron-plate"},
  {id = "north6", kind = "belt", name = "transport-belt", x = 14, y = 6, dir = "north", flow_id = "item/iron-plate"},
  {id = "north5", kind = "belt", name = "transport-belt", x = 14, y = 5, dir = "north", flow_id = "item/iron-plate"},
  {id = "feeder", kind = "belt", name = "transport-belt", x = 14, y = 4, dir = "west", flow_id = "item/iron-plate"},
  {id = "in", kind = "belt", name = "underground-belt", x = 13, y = 4, dir = "north", type = "input", ug_role = "input", ug_pair_id = "out"},
  {id = "out", kind = "belt", name = "underground-belt", x = 13, y = 0, dir = "north", type = "output", ug_role = "output", ug_pair_id = "in"} },
 validator = {catalog = {entity = {}, inserter = {items_per_second = 5, pickup_offset = {x = 0, y = 1}, drop_offset = {x = 0, y = -1}}}},
 feeds = {{tile = {0, 8}, item = "iron-plate"}, {tile = {0, 10}, item = "iron-plate"}},
 sinks = {{tile = {13, 0}, items = {"iron-plate"}}},
 check = "flow_purity", truth = "defect", codes = {"BP_V_UNDERGROUND_SIDELOAD_BLOCKED"},
 audit = {blueprint_audit = {sideload_blocked = 1}},
}
