#!/usr/bin/env python3
"""Decode Factorio's mod-settings.dat and emit a test-only settings mod (round 48 I1).

  tools/mod_settings_dat.py json <mod-settings.dat>             {"version": [...], "startup": {name: value}, ...}
  tools/mod_settings_dat.py mod <mod-settings.dat> <out_dir>    writes <out_dir>/rrc-player-settings_0.0.1/

The generated mod sets every STARTUP setting's default_value in settings-final-fixes.lua, so a headless run with it
loaded starts with the player's startup settings whatever mod-settings.dat the test runner writes itself (pattern
from ~/sushi-packer-mod/tools/stage.sh). Format: version 4 x u16 + u8, then a property tree
(type u8, any-type u8; 1 bool, 2 double, 3 string, 4 list, 5 dictionary, 6 int64, 7 uint64).
"""
import json, os, struct, sys


class Reader:
    def __init__(self, data):
        self.d, self.i = data, 0

    def take(self, n):
        b = self.d[self.i:self.i + n]
        if len(b) != n:
            raise ValueError("mod-settings.dat truncated")
        self.i += n
        return b

    def u8(self): return self.take(1)[0]
    def u16(self): return struct.unpack("<H", self.take(2))[0]
    def u32(self): return struct.unpack("<I", self.take(4))[0]

    def space_u32(self):
        n = self.u8()
        return self.u32() if n == 255 else n

    def string(self):
        if self.u8():  # empty flag
            return ""
        return self.take(self.space_u32()).decode("utf-8")

    def tree(self):
        kind = self.u8()
        self.u8()  # any-type flag
        if kind == 0: return None
        if kind == 1: return self.u8() != 0
        if kind == 2: return struct.unpack("<d", self.take(8))[0]
        if kind == 3: return self.string()
        if kind == 4:
            n = self.u32()
            out = []
            for _ in range(n):
                self.string()
                out.append(self.tree())
            return out
        if kind == 5:
            n = self.u32()
            out = {}
            for _ in range(n):
                k = self.string()
                out[k] = self.tree()
            return out
        if kind == 6: return struct.unpack("<q", self.take(8))[0]
        if kind == 7: return struct.unpack("<Q", self.take(8))[0]
        raise ValueError(f"unknown property tree type {kind} at byte {self.i - 2}")


def decode(path):
    r = Reader(open(path, "rb").read())
    version = [r.u16() for _ in range(4)]
    r.u8()
    tree = r.tree()
    if r.i != len(r.d):
        raise ValueError(f"trailing bytes: read {r.i} of {len(r.d)}")
    flat = {section: {k: (v or {}).get("value") for k, v in (tree.get(section) or {}).items()} for section in tree}
    return {"version": version, **flat}


def lua_value(v):
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return repr(v)
    if isinstance(v, str): return json.dumps(v)
    if isinstance(v, dict): return "{" + ", ".join(f"[{json.dumps(k)}] = {lua_value(x)}" for k, x in sorted(v.items())) + "}"
    if isinstance(v, list): return "{" + ", ".join(lua_value(x) for x in v) + "}"
    if v is None: return "nil"
    raise TypeError(type(v))


def write_mod(path, out_dir):
    s = decode(path)
    d = os.path.join(out_dir, "rrc-player-settings_0.0.1")
    os.makedirs(d, exist_ok=True)
    json.dump({"name": "rrc-player-settings", "version": "0.0.1", "title": "RRC test: player startup settings (never shipped)",
               "author": "rrc tests", "factorio_version": "2.0", "dependencies": ["base"]}, open(os.path.join(d, "info.json"), "w"), indent=2)
    lines = ["--Generated by tools/mod_settings_dat.py from the player's mod-settings.dat; never shipped.",
             "local types = {'bool-setting', 'int-setting', 'double-setting', 'string-setting', 'color-setting'}",
             "local function set(name, value)",
             "    for _, t in ipairs(types) do",
             "        local p = data.raw[t] and data.raw[t][name]",
             "        if p then",
             "            p.default_value = value",
             "            if p.allowed_values then local ok = false; for _, a in ipairs(p.allowed_values) do if a == value then ok = true end end",
             "                if not ok then table.insert(p.allowed_values, value) end end",
             "            if p.minimum_value and type(value) == 'number' and value < p.minimum_value then p.minimum_value = value end",
             "            if p.maximum_value and type(value) == 'number' and value > p.maximum_value then p.maximum_value = value end",
             "            if p.forced_value ~= nil then p.forced_value = value end",
             "            return",
             "        end",
             "    end",
             "end"]
    for k, v in sorted((s.get("startup") or {}).items()):
        lines.append(f"set({json.dumps(k)}, {lua_value(v)})")
    open(os.path.join(d, "settings-final-fixes.lua"), "w").write("\n".join(lines) + "\n")
    print(d, len(s.get("startup") or {}), "startup settings")


if __name__ == "__main__":
    a = sys.argv[1:]
    if len(a) == 2 and a[0] == "json":
        print(json.dumps(decode(a[1]), indent=1, sort_keys=True))
    elif len(a) == 3 and a[0] == "mod":
        write_mod(a[1], a[2])
    else:
        raise SystemExit(__doc__)
